<?php

namespace tests\oihana\arango\models\traits\aql;

use DI\Container;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

use Psr\Log\LoggerInterface;
use Psr\Log\NullLogger;

use oihana\arango\db\enums\AQL;
use oihana\arango\exceptions\RequestValidationException;
use oihana\arango\models\Documents;
use oihana\arango\models\enums\filters\FilterComparator;
use oihana\arango\models\enums\filters\FilterType;
use oihana\enums\http\HttpStatusCode;

/**
 * The AQL every `op` compiles to, for every filter type, pinned character for character.
 *
 * The essays around this one check **fragments** — that the field appears, that an `==`
 * appears somewhere. That is not enough to catch the failure this file exists for: when an
 * operator silently degrades to an equality, an assertion looking for `==` turns **green**.
 * Only the whole expression, compared as a whole, says what the query really means.
 *
 * The matrix is generated by driving a real `Documents` model, so it reads what a caller
 * would get, not what a double was told to answer. Bind tokens carry a random suffix, so
 * they are renumbered in order of appearance (`@v0`, `@v1`, …) before comparison.
 *
 * @package tests\oihana\arango\models\traits\aql
 * @author  Marc Alcaraz
 */
class FilterOperatorMatrixTest extends TestCase
{
    private Documents $model ;

    protected function setUp() :void
    {
        $container = new Container() ;
        $container->set( LoggerInterface::class , new NullLogger() ) ;

        $this->model = new Documents( $container ,
        [
            AQL::COLLECTION => 'items' ,
            AQL::LAZY       => false   ,
            AQL::FILTERS    =>
            [
                'name'    => FilterType::STRING ,
                'age'     => FilterType::NUMBER ,
                'active'  => FilterType::BOOL   ,
                'created' => FilterType::DATE   ,
                'tags'    => FilterType::ARRAY  ,
                'geo'     => FilterType::GEO    ,
            ] ,
        ]) ;
    }

    // ---------------------------------------------------------------- the matrix

    /**
     * Every combination that compiles to what its operator means.
     */
    #[DataProvider( 'soundCombinations' )]
    public function testTheOperatorCompilesToWhatItMeans( string $field , string $op , mixed $value , string $expected ) :void
    {
        $this->assertSame( $expected , $this->compile( $field , $op , $value ) ) ;
    }

    /**
     * The other half of the matrix: an operator this filter type cannot honour is refused,
     * naming what was refused.
     *
     * ⚠ Until 1.6.0 every one of these compiled to an equality. `distance` on a non-geo
     * field, and every function form outside `string` — `contains`, `sw`, `ew`, `regex`
     * and their negations — plus `between` on `bool` and `array`.
     * `{"key":"price","op":"sw","val":12}` asked for prices *starting with* 12 and answered
     * prices *equal to* 12: a handful of plausible rows, in `200`, answering a question
     * nobody asked. An empty page gets noticed; a wrong page does not.
     */
    #[DataProvider( 'refusedCombinations' )]
    public function testAnOperatorTheTypeCannotHonourIsRefused( string $field , string $op , mixed $value ) :void
    {
        try
        {
            $this->compile( $field , $op , $value ) ;
            $this->fail( sprintf( 'the "%s" operator must be refused on "%s"' , $op , $field ) ) ;
        }
        catch ( RequestValidationException $exception )
        {
            $this->assertSame( HttpStatusCode::BAD_REQUEST , $exception->getCode() ) ;
            $this->assertStringContainsString( sprintf( '"%s"' , $op ) , $exception->getMessage() ) ;
        }
    }

    public static function soundCombinations() :array
    {
        return
        [
            'string · eq' => [ 'name' , 'eq' , 'AC' , 'doc.name == @v0' ] ,
            'string · ne' => [ 'name' , 'ne' , 'AC' , 'doc.name != @v0' ] ,
            'string · gt' => [ 'name' , 'gt' , 'AC' , 'doc.name > @v0' ] ,
            'string · ge' => [ 'name' , 'ge' , 'AC' , 'doc.name >= @v0' ] ,
            'string · lt' => [ 'name' , 'lt' , 'AC' , 'doc.name < @v0' ] ,
            'string · le' => [ 'name' , 'le' , 'AC' , 'doc.name <= @v0' ] ,
            'string · in' => [ 'name' , 'in' , [ 'a' , 'b' ] , 'doc.name IN @v0' ] ,
            'string · nin' => [ 'name' , 'nin' , [ 'a' , 'b' ] , 'doc.name NOT IN @v0' ] ,
            'string · like' => [ 'name' , 'like' , 'AC' , 'doc.name LIKE @v0' ] ,
            'string · nlike' => [ 'name' , 'nlike' , 'AC' , 'doc.name NOT LIKE @v0' ] ,
            'string · match' => [ 'name' , 'match' , 'AC' , 'doc.name =~ @v0' ] ,
            'string · nmatch' => [ 'name' , 'nmatch' , 'AC' , 'doc.name !~ @v0' ] ,
            'string · between' => [ 'name' , 'between' , null , '(doc.name >= @v0 && doc.name <= @v1)' ] ,
            'string · contains' => [ 'name' , 'contains' , 'AC' , 'CONTAINS(doc.name,@v0)' ] ,
            'string · ncontains' => [ 'name' , 'ncontains' , 'AC' , '!(CONTAINS(doc.name,@v0))' ] ,
            'string · sw' => [ 'name' , 'sw' , 'AC' , 'STARTS_WITH(doc.name,@v0)' ] ,
            'string · nsw' => [ 'name' , 'nsw' , 'AC' , '!(STARTS_WITH(doc.name,@v0))' ] ,
            'string · ew' => [ 'name' , 'ew' , 'AC' , 'RIGHT(doc.name,CHAR_LENGTH(@v0)) == @v1' ] ,
            'string · new' => [ 'name' , 'new' , 'AC' , '!(RIGHT(doc.name,CHAR_LENGTH(@v0)) == @v1)' ] ,
            'string · regex' => [ 'name' , 'regex' , 'AC' , 'REGEX_TEST(doc.name,@v0)' ] ,
            'string · nregex' => [ 'name' , 'nregex' , 'AC' , '!(REGEX_TEST(doc.name,@v0))' ] ,
            'number · eq' => [ 'age' , 'eq' , 12 , 'doc.age == @v0' ] ,
            'number · ne' => [ 'age' , 'ne' , 12 , 'doc.age != @v0' ] ,
            'number · gt' => [ 'age' , 'gt' , 12 , 'doc.age > @v0' ] ,
            'number · ge' => [ 'age' , 'ge' , 12 , 'doc.age >= @v0' ] ,
            'number · lt' => [ 'age' , 'lt' , 12 , 'doc.age < @v0' ] ,
            'number · le' => [ 'age' , 'le' , 12 , 'doc.age <= @v0' ] ,
            'number · in' => [ 'age' , 'in' , [ 'a' , 'b' ] , 'doc.age IN @v0' ] ,
            'number · nin' => [ 'age' , 'nin' , [ 'a' , 'b' ] , 'doc.age NOT IN @v0' ] ,
            'number · like' => [ 'age' , 'like' , 12 , 'doc.age LIKE @v0' ] ,
            'number · nlike' => [ 'age' , 'nlike' , 12 , 'doc.age NOT LIKE @v0' ] ,
            'number · match' => [ 'age' , 'match' , 12 , 'doc.age =~ @v0' ] ,
            'number · nmatch' => [ 'age' , 'nmatch' , 12 , 'doc.age !~ @v0' ] ,
            'number · between' => [ 'age' , 'between' , null , '(doc.age >= @v0 && doc.age <= @v1)' ] ,
            'bool · eq' => [ 'active' , 'eq' , true , 'doc.active == @v0' ] ,
            'bool · ne' => [ 'active' , 'ne' , true , 'doc.active != @v0' ] ,
            'bool · gt' => [ 'active' , 'gt' , true , 'doc.active > @v0' ] ,
            'bool · ge' => [ 'active' , 'ge' , true , 'doc.active >= @v0' ] ,
            'bool · lt' => [ 'active' , 'lt' , true , 'doc.active < @v0' ] ,
            'bool · le' => [ 'active' , 'le' , true , 'doc.active <= @v0' ] ,
            'bool · in' => [ 'active' , 'in' , [ 'a' , 'b' ] , 'doc.active IN @v0' ] ,
            'bool · nin' => [ 'active' , 'nin' , [ 'a' , 'b' ] , 'doc.active NOT IN @v0' ] ,
            'bool · like' => [ 'active' , 'like' , true , 'doc.active LIKE @v0' ] ,
            'bool · nlike' => [ 'active' , 'nlike' , true , 'doc.active NOT LIKE @v0' ] ,
            'bool · match' => [ 'active' , 'match' , true , 'doc.active =~ @v0' ] ,
            'bool · nmatch' => [ 'active' , 'nmatch' , true , 'doc.active !~ @v0' ] ,
            'date · eq' => [ 'created' , 'eq' , '2026-01-01' , 'doc.created == @v0' ] ,
            'date · ne' => [ 'created' , 'ne' , '2026-01-01' , 'doc.created != @v0' ] ,
            'date · gt' => [ 'created' , 'gt' , '2026-01-01' , 'doc.created > @v0' ] ,
            'date · ge' => [ 'created' , 'ge' , '2026-01-01' , 'doc.created >= @v0' ] ,
            'date · lt' => [ 'created' , 'lt' , '2026-01-01' , 'doc.created < @v0' ] ,
            'date · le' => [ 'created' , 'le' , '2026-01-01' , 'doc.created <= @v0' ] ,
            'date · in' => [ 'created' , 'in' , [ 'a' , 'b' ] , 'doc.created IN @v0' ] ,
            'date · nin' => [ 'created' , 'nin' , [ 'a' , 'b' ] , 'doc.created NOT IN @v0' ] ,
            'date · like' => [ 'created' , 'like' , '2026-01-01' , 'doc.created LIKE @v0' ] ,
            'date · nlike' => [ 'created' , 'nlike' , '2026-01-01' , 'doc.created NOT LIKE @v0' ] ,
            'date · match' => [ 'created' , 'match' , '2026-01-01' , 'doc.created =~ @v0' ] ,
            'date · nmatch' => [ 'created' , 'nmatch' , '2026-01-01' , 'doc.created !~ @v0' ] ,
            'date · between' => [ 'created' , 'between' , null , '(doc.created >= @v0 && doc.created <= @v1)' ] ,
            'array · eq' => [ 'tags' , 'eq' , 'AC' , 'doc.tags == @v0' ] ,
            'array · ne' => [ 'tags' , 'ne' , 'AC' , 'doc.tags != @v0' ] ,
            'array · gt' => [ 'tags' , 'gt' , 'AC' , 'doc.tags > @v0' ] ,
            'array · ge' => [ 'tags' , 'ge' , 'AC' , 'doc.tags >= @v0' ] ,
            'array · lt' => [ 'tags' , 'lt' , 'AC' , 'doc.tags < @v0' ] ,
            'array · le' => [ 'tags' , 'le' , 'AC' , 'doc.tags <= @v0' ] ,
            'array · in' => [ 'tags' , 'in' , [ 'a' , 'b' ] , 'doc.tags IN @v0' ] ,
            'array · nin' => [ 'tags' , 'nin' , [ 'a' , 'b' ] , 'doc.tags NOT IN @v0' ] ,
            'array · like' => [ 'tags' , 'like' , 'AC' , 'doc.tags LIKE @v0' ] ,
            'array · nlike' => [ 'tags' , 'nlike' , 'AC' , 'doc.tags NOT LIKE @v0' ] ,
            'array · match' => [ 'tags' , 'match' , 'AC' , 'doc.tags =~ @v0' ] ,
            'array · nmatch' => [ 'tags' , 'nmatch' , 'AC' , 'doc.tags !~ @v0' ] ,
        ] ;
    }

    public static function refusedCombinations() :array
    {
        return
        [
            'string · distance' => [ 'name' , 'distance' , 'AC' ] ,
            'number · contains' => [ 'age' , 'contains' , 12 ] ,
            'number · ncontains' => [ 'age' , 'ncontains' , 12 ] ,
            'number · sw' => [ 'age' , 'sw' , 12 ] ,
            'number · nsw' => [ 'age' , 'nsw' , 12 ] ,
            'number · ew' => [ 'age' , 'ew' , 12 ] ,
            'number · new' => [ 'age' , 'new' , 12 ] ,
            'number · regex' => [ 'age' , 'regex' , 12 ] ,
            'number · nregex' => [ 'age' , 'nregex' , 12 ] ,
            'number · distance' => [ 'age' , 'distance' , 12 ] ,
            'bool · between' => [ 'active' , 'between' , null ] ,
            'bool · contains' => [ 'active' , 'contains' , true ] ,
            'bool · ncontains' => [ 'active' , 'ncontains' , true ] ,
            'bool · sw' => [ 'active' , 'sw' , true ] ,
            'bool · nsw' => [ 'active' , 'nsw' , true ] ,
            'bool · ew' => [ 'active' , 'ew' , true ] ,
            'bool · new' => [ 'active' , 'new' , true ] ,
            'bool · regex' => [ 'active' , 'regex' , true ] ,
            'bool · nregex' => [ 'active' , 'nregex' , true ] ,
            'bool · distance' => [ 'active' , 'distance' , true ] ,
            'date · contains' => [ 'created' , 'contains' , '2026-01-01' ] ,
            'date · ncontains' => [ 'created' , 'ncontains' , '2026-01-01' ] ,
            'date · sw' => [ 'created' , 'sw' , '2026-01-01' ] ,
            'date · nsw' => [ 'created' , 'nsw' , '2026-01-01' ] ,
            'date · ew' => [ 'created' , 'ew' , '2026-01-01' ] ,
            'date · new' => [ 'created' , 'new' , '2026-01-01' ] ,
            'date · regex' => [ 'created' , 'regex' , '2026-01-01' ] ,
            'date · nregex' => [ 'created' , 'nregex' , '2026-01-01' ] ,
            'date · distance' => [ 'created' , 'distance' , '2026-01-01' ] ,
            'array · between' => [ 'tags' , 'between' , null ] ,
            'array · contains' => [ 'tags' , 'contains' , 'AC' ] ,
            'array · ncontains' => [ 'tags' , 'ncontains' , 'AC' ] ,
            'array · sw' => [ 'tags' , 'sw' , 'AC' ] ,
            'array · nsw' => [ 'tags' , 'nsw' , 'AC' ] ,
            'array · ew' => [ 'tags' , 'ew' , 'AC' ] ,
            'array · new' => [ 'tags' , 'new' , 'AC' ] ,
            'array · regex' => [ 'tags' , 'regex' , 'AC' ] ,
            'array · nregex' => [ 'tags' , 'nregex' , 'AC' ] ,
            'array · distance' => [ 'tags' , 'distance' , 'AC' ] ,
        ] ;
    }

    // ---------------------------------------------------------------- the matrix cannot go stale

    /**
     * A guard over the source rather than over one behaviour: every operator the public
     * catalogue declares appears in the matrix, for every type that has one. Add an
     * operator to `FilterComparator` without a line here and this essay says so — which is
     * the only way a matrix stays a matrix.
     */
    public function testTheMatrixCoversEveryDeclaredOperator() :void
    {
        $declared = array_values( array_filter
        (
            FilterComparator::getAll() ,
            static fn( string $name ) => !str_starts_with( $name , '__' ) ,
            ARRAY_FILTER_USE_KEY
        ) ) ;

        $covered = [] ;
        foreach ( [ ...self::soundCombinations() , ...self::refusedCombinations() ] as $case )
        {
            $covered[ $case[ 1 ] ] = true ;
        }

        $missing = array_values( array_diff( $declared , array_keys( $covered ) ) ) ;

        // Not vacuous: an empty catalogue would satisfy the diff above without measuring anything.
        $this->assertGreaterThanOrEqual( 22 , count( $declared ) ) ;
        $this->assertSame( [] , $missing , 'every declared operator must appear in the matrix' ) ;
    }

    /**
     * The five comparator types are each measured against the whole catalogue — 22
     * operators apiece. `geo` is not one of them: it ignores `op` entirely and answers to
     * its own contract, below.
     */
    public function testEveryTypeIsMeasuredAgainstTheWholeCatalogue() :void
    {
        $perType = [] ;
        foreach ( [ ...self::soundCombinations() , ...self::refusedCombinations() ] as $name => $case )
        {
            $perType[ explode( ' ' , (string) $name )[ 0 ] ][] = $case[ 1 ] ;
        }

        $this->assertCount( 5 , $perType ) ;

        foreach ( $perType as $type => $ops )
        {
            $this->assertCount( 22 , array_unique( $ops ) , "the $type type is not fully measured" ) ;
        }
    }

    // ---------------------------------------------------------------- the two contracts that are not operators

    /**
     * No `op` at all is an equality — that is the documented default, and the one case
     * where falling back to `==` is what the caller meant.
     */
    public function testAnAbsentOperatorIsAnEquality() :void
    {
        $this->assertSame( 'doc.name == @v0' , $this->compile( 'name' , null , 'AC' ) ) ;
    }

    /**
     * The geo filter answers to `min` / `max` rather than to `op`, and emits nothing at all
     * without a radius — documented, and the one legitimately empty cell of the matrix.
     */
    public function testTheGeoFilterAnswersToItsOwnContract() :void
    {
        $point = [ 'latitude' => 48.85 , 'longitude' => 2.35 ] ;

        $this->assertSame
        (
            'DISTANCE(doc.geo.latitude,doc.geo.longitude,@v0,@v1) <= @v2' ,
            $this->compile( 'geo' , 'distance' , $point , [ 'max' => 5000 ] )
        ) ;

        // No radius, no clause — a filter that cannot be honoured is not silently widened.
        $this->assertSame( '' , $this->compile( 'geo' , 'distance' , $point ) ) ;
    }

    // ---------------------------------------------------------------- the two array forms

    /**
     * `?quant=` carried the same default. `{"key":"tags","quant":"any","op":"zzz"}` used to
     * compile to `tags ANY == @v` — the quantifier honoured, the comparison invented.
     */
    public function testAQuantifiedFilterRefusesAnUnknownOperator() :void
    {
        $this->expectException( RequestValidationException::class ) ;
        $this->expectExceptionMessage( 'Unsupported filter operator "zzz"' ) ;

        $binds = [] ;
        $this->model->prepareFilter( [ 'key' => 'tags' , 'quant' => 'any' , 'op' => 'zzz' , 'val' => 'AC' ] , $binds ) ;
    }

    /**
     * And so did `atLeast.<op>`: a mistyped code became `at least (n) ==`.
     */
    public function testAnAtLeastFilterRefusesAnUnknownOperator() :void
    {
        $this->expectException( RequestValidationException::class ) ;
        $this->expectExceptionMessage( 'Unsupported filter operator "zzz"' ) ;

        $binds = [] ;
        $this->model->prepareFilter( [ 'key' => 'tags' , 'op' => [ 'atLeast.zzz' , 2 ] , 'val' => 'AC' ] , $binds ) ;
    }

    /**
     * ⚠ A shape rather than a spelling: an operator handed as a list the router does not
     * recognise reached `__ALIAS__[ $op ]` and raised a **TypeError** — a PHP fatal, for a
     * malformed request. It is a refusal like any other now.
     */
    public function testAnOperatorOfTheWrongShapeIsRefusedRatherThanFatal() :void
    {
        $this->expectException( RequestValidationException::class ) ;

        $binds = [] ;
        $this->model->prepareFilter( [ 'key' => 'tags' , 'op' => [ 'zzz' , 2 ] , 'val' => 'AC' ] , $binds ) ;
    }

    /**
     * The `atLeast` form still honours a code it can translate.
     */
    public function testAnAtLeastFilterKeepsTheOperatorsItUnderstands() :void
    {
        $binds = [] ;
        $out   = (string) $this->model->prepareFilter( [ 'key' => 'tags' , 'op' => [ 'atLeast.ge' , 2 ] , 'val' => 'AC' ] , $binds ) ;

        $this->assertStringContainsString( 'AT LEAST (2) >=' , $out ) ;
    }

    /**
     * The quantified form still honours an operator it can translate.
     */
    public function testAQuantifiedFilterKeepsTheOperatorsItUnderstands() :void
    {
        $this->assertSame( 'doc.tags ANY >= @v0' , $this->compile( 'tags' , 'ge' , 'AC' , [ 'quant' => 'any' ] ) ) ;
    }

    // ---------------------------------------------------------------- harness

    /**
     * Compiles one filter and renumbers its bind tokens, which carry a random suffix.
     */
    private function compile( string $field , ?string $op , mixed $value , array $extra = [] ) :string
    {
        $init = [ 'key' => $field , ...$extra ] ;

        if ( $op !== null )
        {
            $init[ 'op' ] = $op ;
        }

        if ( $op === 'between' )
        {
            $init[ 'min' ] = 1 ;
            $init[ 'max' ] = 9 ;
        }
        else
        {
            $init[ 'val' ] = $value ;
        }

        $binds = [] ;
        $index = 0 ;

        return (string) preg_replace_callback
        (
            '/@query_\\d+_\\d+/' ,
            static function () use ( &$index ) { return '@v' . $index++ ; } ,
            (string) $this->model->prepareFilter( $init , $binds )
        ) ;
    }
}
