<?php

namespace tests\oihana\arango\db\binds;

use oihana\exceptions\BindException;
use PHPUnit\Framework\TestCase;
use function oihana\arango\db\binds\aqlBind;
use function oihana\arango\db\binds\aqlBindCollection;

class AqlBindTest extends TestCase
{
    /**
     * @throws BindException
     */
    public function testAqlBind(): void
    {
        $binds = [];
        $result = aqlBind('foo', $binds, 'my_var');
        $this->assertSame('@my_var', $result);
        $this->assertSame(['my_var' => 'foo'], $binds);
    }

    /**
     * @throws BindException
     */
    public function testAqlBindWithNullToAndPrefix(): void
    {
        $binds = [];
        $result = aqlBind('foo', $binds, null , 'var' ) ;
        $this->assertMatchesRegularExpression('/^@var_[0-9]{6}$/', $result);

        $key = ltrim($result,'@') ;

        $this->assertArrayHasKey( $key , $binds ) ;
        $this->assertSame('foo', $binds[$key]);
    }

    /**
     * @throws BindException
     */
    public function testAqlBindWithNullToAndNullPrefix(): void
    {
        $binds = [];
        $result = aqlBind('foo', $binds ) ;
        $this->assertMatchesRegularExpression('/^@q_[0-9]{6}$/', $result);

        $key = ltrim($result,'@') ;

        $this->assertArrayHasKey( $key , $binds ) ;
        $this->assertSame('foo', $binds[$key]);
    }

    /**
     * @throws BindException
     */
    public function testAqlBindCollection(): void
    {
        $binds = [];
        $result = aqlBindCollection('my_collection', $binds, 'my_coll');
        $this->assertSame('@@my_coll', $result);
        $this->assertSame(['@my_coll' => 'my_collection'], $binds);
    }

    /**
     * @throws BindException
     */
    public function testBindAqlCollectionWithNullToAndWithNullPrefix(): void
    {
        $binds = [];
        $result = aqlBindCollection('my_collection', $binds );
        $this->assertMatchesRegularExpression('/^@@c_[0-9]{6}$/', $result);

        $key = substr($result, 1);

        $this->assertArrayHasKey( $key , $binds ) ;
        $this->assertSame('my_collection', $binds[$key]);
    }

    // ========================================
    // NAME COLLISIONS
    // ========================================

    /**
     * An auto-generated name is drawn until the slot is free. The single draw the
     * function used to make could land on a name already taken — 900 000 values, one
     * shared prefix per query — and the loser was overwritten in silence.
     *
     * The draw is seeded so the collision is provoked rather than waited for.
     *
     * @throws BindException
     */
    public function testAnAutoGeneratedNameNeverLandsOnATakenSlot(): void
    {
        mt_srand( 1 ) ;
        $taken = 'q_' . mt_rand( 100000 , 999999 ) ; // the very name the next draw will produce
        mt_srand( 1 ) ;                              // rewind, so aqlBind() draws it first

        $binds  = [ $taken => 'first' ] ;
        $result = aqlBind( 'second' , $binds ) ;

        $this->assertNotSame( '@' . $taken , $result ) ;        // it redrew
        $this->assertSame( 'first' , $binds[ $taken ] ) ;       // and overwrote nothing
        $this->assertCount( 2 , $binds ) ;
        $this->assertSame( 'second' , $binds[ ltrim( $result , '@' ) ] ) ;
    }

    /**
     * An explicit name already bound to a **different** value raises: replacing it
     * would silently change what the query asks for.
     *
     * @throws BindException
     */
    public function testAnExplicitNameBoundToADifferentValueRaises(): void
    {
        $binds = [] ;
        aqlBind( 'first' , $binds , 'my_var' ) ;

        $this->expectException( BindException::class ) ;
        $this->expectExceptionMessage( 'The bind variable "my_var" is already bound to a different value' ) ;

        aqlBind( 'second' , $binds , 'my_var' ) ;
    }

    /**
     * Rebinding the **same** value drops nothing, so it stays allowed — two builders
     * sharing one bind map must not fail on a no-op.
     *
     * @throws BindException
     */
    public function testRebindingTheSameValueIsAllowed(): void
    {
        $binds = [] ;
        $this->assertSame( '@my_var' , aqlBind( 'foo' , $binds , 'my_var' ) ) ;
        $this->assertSame( '@my_var' , aqlBind( 'foo' , $binds , 'my_var' ) ) ;
        $this->assertSame( [ 'my_var' => 'foo' ] , $binds ) ;
    }

    /**
     * The comparison is strict, so a number and its string form count as two
     * different values — AQL compares `1` and `"1"` differently, and letting the
     * second overwrite the first would change the meaning of the query.
     *
     * @throws BindException
     */
    public function testANumberAndItsStringFormCountAsDifferentValues(): void
    {
        $binds = [] ;
        aqlBind( 1 , $binds , 'threshold' ) ;

        $this->expectException( BindException::class ) ;
        aqlBind( '1' , $binds , 'threshold' ) ;
    }

    /**
     * The guard reads the same key the write uses, so a collection bind (`@@name`)
     * is protected too rather than slipping past on its prefix.
     *
     * @throws BindException
     */
    public function testACollectionNameIsGuardedOnItsPrefixedKey(): void
    {
        $binds = [] ;
        $this->assertSame( '@@collection' , aqlBindCollection( 'users' , $binds , 'collection' ) ) ;
        $this->assertSame( '@@collection' , aqlBindCollection( 'users' , $binds , 'collection' ) ) ; // same value, allowed
        $this->assertSame( [ '@collection' => 'users' ] , $binds ) ;

        $this->expectException( BindException::class ) ;
        aqlBindCollection( 'orders' , $binds , 'collection' ) ;
    }

}