<?php
/**
 * Convert a PHPUnit Clover coverage report into a readable Markdown summary.
 *
 * Usage:
 *   php tools/clover-to-markdown.php [clover.xml] [out.md]
 *
 * Defaults:
 *   clover.xml -> build/coverage/clover.xml
 *   out.md     -> build/coverage/COVERAGE.md
 *
 * The output is intentionally NOT committed (build/ is gitignored): a coverage
 * snapshot goes stale at the very next commit. Regenerate it on demand with
 * `composer coverage:md`.
 */

$cloverPath = $argv[1] ?? 'build/coverage/clover.xml';
$outPath    = $argv[2] ?? 'build/coverage/COVERAGE.md';

if ( !is_file( $cloverPath ) )
{
    fwrite( STDERR, "Clover report not found: {$cloverPath}\n" );
    fwrite( STDERR, "Run `composer coverage` first to generate it.\n" );
    exit( 1 );
}

$xml  = simplexml_load_file( $cloverPath );
$root = realpath( getcwd() ) . '/';

// --- Per-file metrics -------------------------------------------------------

$files = [];

foreach ( $xml->xpath( '//file' ) as $f )
{
    $rel = str_replace( $root , '' , (string) $f['name'] );
    $m   = $f->metrics;

    $st  = (int) $m['statements'];
    $cst = (int) $m['coveredstatements'];

    $files[] = [
        'rel' => $rel ,
        'st'  => $st ,
        'cst' => $cst ,
        'me'  => (int) $m['methods'] ,
        'cme' => (int) $m['coveredmethods'] ,
        'pct' => $st ? $cst / $st * 100 : 100.0 ,
    ];
}

// --- Group by directory under src/oihana/arango ----------------------------

$dirs = [];

foreach ( $files as $f )
{
    $d = preg_replace( '#^src/oihana/arango/?#' , '' , dirname( $f['rel'] ) );
    if ( $d === '' || $d === '.' ) { $d = '(root)'; }

    $dirs[ $d ]['st']  = ( $dirs[ $d ]['st']  ?? 0 ) + $f['st'];
    $dirs[ $d ]['cst'] = ( $dirs[ $d ]['cst'] ?? 0 ) + $f['cst'];
    $dirs[ $d ]['me']  = ( $dirs[ $d ]['me']  ?? 0 ) + $f['me'];
    $dirs[ $d ]['cme'] = ( $dirs[ $d ]['cme'] ?? 0 ) + $f['cme'];
}

// --- Project totals ---------------------------------------------------------

$pr   = $xml->xpath( '//project/metrics' )[0];
$tSt  = (int) $pr['statements'];
$tCst = (int) $pr['coveredstatements'];
$tMe  = (int) $pr['methods'];
$tCme = (int) $pr['coveredmethods'];

$bar = static fn( float $p ): string =>
    str_repeat( '#' , (int) round( $p / 10 ) ) . str_repeat( '.' , 10 - (int) round( $p / 10 ) );

// --- Render -----------------------------------------------------------------

$o   = [];
$o[] = '# Test coverage report';
$o[] = '';
$o[] = '> Generated by `composer coverage:md` (PHPUnit Clover -> Markdown).';
$o[] = '> Not committed: `build/` is gitignored. Regenerate on demand.';
$o[] = '';
$o[] = '## Summary';
$o[] = '';
$o[] = '| Metric | Coverage | |';
$o[] = '|---|---|---|';
$o[] = sprintf( '| **Lines** | %.2f%% (%d/%d) | `%s` |'   , $tSt ? $tCst / $tSt * 100 : 100 , $tCst , $tSt , $bar( $tSt ? $tCst / $tSt * 100 : 100 ) );
$o[] = sprintf( '| **Methods** | %.2f%% (%d/%d) | `%s` |' , $tMe ? $tCme / $tMe * 100 : 100 , $tCme , $tMe , $bar( $tMe ? $tCme / $tMe * 100 : 100 ) );
$o[] = '';
$o[] = '## Coverage by directory (lines)';
$o[] = '';
$o[] = '| Directory | Lines | Methods | |';
$o[] = '|---|---|---|---|';

uasort( $dirs , static fn( $a , $b ) =>
    ( $a['st'] ? $a['cst'] / $a['st'] : 1 ) <=> ( $b['st'] ? $b['cst'] / $b['st'] : 1 ) );

foreach ( $dirs as $d => $v )
{
    if ( !$v['st'] ) { continue; }

    $p  = $v['cst'] / $v['st'] * 100;
    $mp = $v['me'] ? $v['cme'] / $v['me'] * 100 : 100;

    $o[] = sprintf( '| `%s` | %.1f%% (%d/%d) | %.1f%% (%d/%d) | `%s` |' ,
        $d , $p , $v['cst'] , $v['st'] , $mp , $v['cme'] , $v['me'] , $bar( $p ) );
}

$o[] = '';
$o[] = '## 20 least-covered files (priority targets)';
$o[] = '';
$o[] = '| File | Lines | Methods |';
$o[] = '|---|---|---|';

usort( $files , static fn( $a , $b ) => [ $a['pct'] , $a['st'] ] <=> [ $b['pct'] , $b['st'] ] );

$n = 0;

foreach ( $files as $f )
{
    if ( $f['st'] === 0 || $f['pct'] >= 100 ) { continue; }

    $o[] = sprintf( '| `%s` | %.1f%% (%d/%d) | %d/%d |' ,
        $f['rel'] , $f['pct'] , $f['cst'] , $f['st'] , $f['cme'] , $f['me'] );

    if ( ++$n >= 20 ) { break; }
}

$o[] = '';
$o[] = '## Files at 0% (never touched by a test)';
$o[] = '';

$zero = array_filter( $files , static fn( $f ) => $f['st'] > 0 && $f['cst'] === 0 );

if ( !$zero )
{
    $o[] = '_None — every file with executable code is touched at least once._';
}
else
{
    foreach ( $zero as $f )
    {
        $o[] = sprintf( '- `%s` (%d statements)' , $f['rel'] , $f['st'] );
    }
}

$o[] = '';

$dir = dirname( $outPath );
if ( !is_dir( $dir ) ) { mkdir( $dir , 0o775 , true ); }

file_put_contents( $outPath , implode( "\n" , $o ) . "\n" );

echo "Coverage Markdown written to {$outPath}\n";
